### ISSUE TITLE
Upgrade peerDependencies to support React >= 17

### ISSUE THREAD

**Issue by nishila2** [product-ride/storybook-addon-vscode-source#3]
as npm >= 7 is strict about package dependencies, getting errors while installing this package in a project which uses react version >= 17. is there any plan to upgrade this to react >= 17

**Comment by nishila2** [comment]
@coderkevin  or @vilvaathibanpb  could you please have a look at this issue

**Comment by vilvaathibanpb** [comment]
@nishila2 thanks for bringing it to our attention. If you want to contribute and upgrade you are welcome to send a PR. Otherwise we will fix it soon

**Comment by nishila2** [comment]
@vilvaathibanpb or @coderkevin Please check the PR I have created.

**Comment by vilvaathibanpb** [comment]
Fixed: https://github.com/product-ride/storybook-addon-vscode-source/commit/4aad1ad844494a41f8da8548e8c7d6453052980b
